language: java

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

script:
  - mvn clean package jacoco:report coveralls:jacoco
  - mvn -f math-plugin/pom.xml clean package jacoco:report
  - mvn -f string-plugin/pom.xml clean package jacoco:report
